proxy-providers: {}
proxy-groups:
  - name: Netflix
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Netflix.png
    type: select
    proxies:
      - DIRECT
  - name: Crunchyroll
    icon: https://upload.wikimedia.org/wikipedia/commons/0/08/Crunchyroll_Logo.png
    type: select
    proxies:
      - DIRECT
  - name: Spotify
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Spotify.png
    type: select
    proxies:
      - DIRECT
  - name: YouTube
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/YouTube.png
    type: select
    proxies:
      - DIRECT
  - name: Speedtest
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Speedtest.png
    type: select
    proxies:
      - DIRECT
rules:
  - SCRIPT,quic,REJECT
  # Netflix
  - GEOSITE,netflix,Netflix
  # Disney+
  - GEOSITE,disney,Disney+
  # Spotify
  - GEOSITE,spotify,Spotify
  # Speedtest
  - GEOSITE,speedtest,Speedtest
  # GitHub
  - GEOSITE,github,选择代理
  # Telegram
  - IP-ASN,62014,选择代理,no-resolve
  - IP-ASN,59930,选择代理,no-resolve
  - IP-ASN,44907,选择代理,no-resolve
  - IP-ASN,211157,选择代理,no-resolve
  - PROCESS-NAME,Telegram.exe,选择代理
  - PROCESS-NAME,Telegram,选择代理
  - GEOSITE,telegram,选择代理
  # YouTube
  - GEOSITE,youtube,YouTube
  # Google
  - GEOSITE,google,选择代理
  # Twitter
  - GEOSITE,twitter,选择代理
  - DOMAIN-SUFFIX,tapbots.com,选择代理
  # Instagram
  - GEOSITE,instagram,选择代理
  # Facebook
  - GEOSITE,facebook,选择代理
  # Steam
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,steam,选择代理
  # Apple LBS
  - DOMAIN-SUFFIX,iphone-ld.apple.com,DIRECT
  - DOMAIN-SUFFIX,lcdn-locator.apple.com,DIRECT
  - DOMAIN-SUFFIX,lcdn-registration.apple.com,DIRECT
  - DOMAIN-SUFFIX,push.apple.com,DIRECT
  # Apple OCSP
  - PROCESS-NAME,trustd,选择代理
  # Microsoft
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,microsoft,选择代理
  - GEOSITE,xbox,选择代理
  # common proxy utils
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,CloudflareWARP,DIRECT
  - PROCESS-NAME,Cloudflare WARP,DIRECT
  - IP-CIDR,162.159.193.0/24,DIRECT,no-resolve
  - PROCESS-NAME,p4pclient,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qbittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,默认
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
log-level: warning
mode: rule
proxies: [{name: LRHS Pro, network: ws, password: "pass", port: 443, server: ip, type: vless, ws-opts: {headers: {}, path: ""}, benchmark-url: 'https://google.com', alterId: 0, cipher: "auto", flow: "", uuid: b05882d1-a3c6-4623-b26f-a4ef1ccab4ec, tls: null}]
